<a href="https://colab.research.google.com/github/DioBrandon31/Metodos-numericos/blob/main/APS%20Q4%20Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Matriz A
A = np.array([[3, 2, 7], [2, 5, 7], [7, 1, 8]])

# Autovalores e autovetores de A
autovalores, autovetores = np.linalg.eig(A)

# Resultados
print("Autovalores de A: ", autovalores)
print("Autovetores de A: \n", autovetores)

# Decomposição SVD de A
U, S, Vt = np.linalg.svd(A)

# Resultados
print("Matriz U da decomposição SVD: \n", U)
print("Matriz S da decomposição SVD: ", S)
print("Matriz Vt da decomposição SVD: \n", Vt)

Autovalores de A:  [14.35631335 -1.47439425  3.11808089]
Autovetores de A: 
 [[-0.49765377 -0.71770766 -0.05354039]
 [-0.58529731 -0.39690103 -0.96038303]
 [-0.64013107  0.57215844  0.27349199]]
Matriz U da decomposição SVD: 
 [[-0.51122121 -0.08505854 -0.85522975]
 [-0.53607734 -0.74623202  0.39466297]
 [-0.67176928  0.66022937  0.33589168]]
Matriz S da decomposição SVD:  [15.29608356  4.36493456  0.98852112]
Matriz Vt da decomposição SVD: 
 [[-0.47778264 -0.28599467 -0.83062073]
 [ 0.6584213  -0.74251922 -0.12307149]
 [ 0.58155407  0.6056998  -0.54306778]]
